name: 'Merge Queue init'
description: 'handles a merge queue'
inputs:
  init_trigger:
    description: 'the trigger keyword to add PR to queue'
    required: false
    default: '/merging'
  channel:
    description: 'the channel to use as the queue'
    required: false
    default: 'merge-queue'
  merge_ready_message:
    description: 'message for alerting next PR in the queue'
    required: false
    default: 'ready to merge!'
  mode:
    description: 'mode of the action, changes behaviour based on mode'
    required: true
outputs:
  status: 
    description: 'status of the build run: TRIGGER_NOT_FOUND, ALREADY_CLOSED, ALREADY_QUEUED, ADDED_TO_QUEUE, FAILURE'
  next_pr: 
    description: 'id number of next pull request in the queue'
runs:
  using: 'node12'
  main: 'src/index.js'