name: 'Slack Merge Queue'
branding:
  icon: 'bell'
  color: 'green'
description: 'handles a merge queue within slack'
inputs:
  mode:
    description: 'mode of the action, changes behaviour based on mode'
    required: true
  channel:
    description: 'the channel to use as the queue'
    required: false
  channel_id:
    description: 'the channel id to use as the queue'
    required: false
  icon_emoji:
    description: 'icon emoji for the bot'
    required: false
    default: ':robot_face:'
  init_trigger:
    description: 'the trigger keyword to add PR to queue'
    required: false
    default: '/merging'
  merge_ready_message:
    description: 'message for alerting next PR in the queue'
    required: false
    default: 'Last PR closed. This PR is now up for merge!'
  cancel_trigger:
    description: 'the trigger keyword to manually cancel PR in queue'
    required: false
    default: '/cancel-merge'
  cancel_ready_message:
    description: 'message for alerting next PR in the queue after manual cancel'
    required: false
    default: 'Previous PR merge was temporarily cancelled. This PR is now up for merge!'
  alert_message:
    description: 'message for alerting current PR in the queue'
    required: false
    default: 'build is complete. Time to merge!'
  only_when_current:
    description: 'ALERT MODE: only alert if PR is currently up for merge'
    required: false
    default: 'true'
  auto_notify:
    description: 'INIT MODE: auto notify relayed guthub users'
    required: false
    default: 'true'
  delete_on_cancel:
    description: 'delete queue item when cancelled'
    required: false
    default: 'false'
  history_threshold:
    description: 'delete queue item when cancelled'
    required: false
    default: '10'
  channel_types:
    description: 'channel types to include in the request'
    required: false
    default: 'public_channel,private_channel'
  team_id:
    description: 'encoded Slack team id to list channels in'
    required: false

outputs:
  status: 
    description: 'status of the build run'
  triggered: 
    description: 'boolean for when a comment triggers an action'
  next_pr: 
    description: 'id number of next pull request in the queue'
runs:
  using: 'node20'
  main: 'src/index.js'