name: 'Merge Queue init'
description: 'handles a merge queue'
inputs:
  trigger:  # id of input
    description: 'the trigger keyword to add PR to queue'
    required: false
    default: '/merging'
outputs:
  isTriggered: # id of output
    description: 'if the process is triggered'
runs:
  using: 'node12'
  main: 'dist/index.js'