name: test_add_to_q

on:
  issue_comment:
    types: [created, edited]

jobs:
  add_to_queue:
    env: # Or as an environment variable
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    runs-on: ubuntu-latest
    name: Add PR to queue
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add PR to queue
        uses: ./ # Uses an action in the root directory
        id: add_to_q
        with:
          init_trigger: '/merging'
          mode: 'INIT'
      # Use the output from the `add_to_q` step
      - name: Get the output
        run: echo "status => ${{ steps.add_to_q.outputs.status }}"