name: test_add_to_q

on:
  issue_comment:
    types: [created, edited]

jobs:
  add_to_queue:
    runs-on: ubuntu-latest
    name: Add PR to queue
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add PR to queue
        uses: ./ # Uses an action in the root directory
        id: add_to_q
        with:
          trigger: '/merging'
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "The time was ${{ steps.add_to_q.outputs.isTriggered }}"